# Data cleaning with pandas 
## Following Alex The Analyst YouTube turorial

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(r"C:\Users\Admin\OneDrive\Documents\Alex the analyst series\Python\Pandas data cleaning\Customer Call List.xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

## The goal is to clean this data set so that it can be given to call centre employes.
### First dropping any duplucates

In [3]:
df = df.drop_duplicates()

### Now removing any unneeded columns.

In [4]:
df = df.drop(columns = 'Not_Useful_Column')

### Now going column by column to see what needs fixing. Staring from the left. 
#### Customer ID and First_name look fine. Last_Name has some problems. Using str.strip to remove the punctuation from the last names. (note: the strip function is from regular expression which can get complex so here each punctuation is taken out one by one using the left or right string strip)
#### note: it is important that only the column being worked on is updated. In this case the Last_Name column is updated. if the whole data frame is updated, all other columns would be erased as the function being used is only working on the Last_Name column.

In [5]:
df['Last_Name'] = df['Last_Name'].str.lstrip('...')
df['Last_Name'] = df['Last_Name'].str.lstrip('/')
df['Last_Name'] = df['Last_Name'].str.rstrip('_')

#### To run all of this in one line you can use the following

In [6]:
# df['Last_Name'] = df['Last_Name'].str.strip('123._/')

#### Moving on to the Phone_Number column. 
#### First non numeric values will be removed then the phone numbers will be formatted in a standardised way.

In [7]:
# anything that is not alphabetic values upper or lower and numbers 0-9 will be replaced with nothing.
df['Phone_Number'] = df['Phone_Number'].str.replace('[^a-zA-Z0-9]', '')

C:\Users\Admin\AppData\Local\Temp\ipykernel_2580\3197584274.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Phone_Number'] = df['Phone_Number'].str.replace('[^a-zA-Z0-9]', '')

#### Now the Phone numbers are just plane numbers the chosen formatting can be added in.
#### Adding in the formatting. 
#### First the values in the Phone Number column need to be changed to strings (they are currently numbers). To do this, the string coversion needs to applyed to each individual value. Applying the string convertion to the entire column wont work (this wont work: str(df['Phone_Number)']).

In [8]:
df['Phone_Number'] = df['Phone_Number'].apply(lambda x: str(x))  #This could be done in a for loop but lambda is quicker.
df['Phone_Number'] = df['Phone_Number'].apply(lambda x: x[0:3]+'-' + x[3:6]+'-' + x[6:10] )

#### Now the NA values can be removed

In [9]:
df['Phone_Number'] = df['Phone_Number'].str.replace('nan--', '')
df['Phone_Number'] = df['Phone_Number'].str.replace('Na--', '')

#### Moving on to the Adress column. 
#### The adress column will be split so that the zip code has its own column to make it more readable for the call centre staff

In [10]:
df[['Street_Address', 'State', 'Zip_Code']]=df['Address'].str.split(',', 2, expand = True)

#### Now the formatting for the Paying Customer column will be standardised. Same for the Do Not Contact column.

In [11]:
df['Paying Customer'] = df['Paying Customer'].str.replace('Yes', 'Y')
df['Paying Customer'] = df['Paying Customer'].str.replace('No', 'N')

df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('Yes', 'Y')
df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('No', 'N')

### Now all the individual columns are fixed, the data set as a whole can be considered. 
### Now all the NA and NaN values can be standardised

In [12]:
df = df.replace('N/A','' )
df = df.replace('N/a','' )
df = df.fillna('') #the NaN values are not actually values, they are nulls so must be treated differently

# The data set is now cleaned

In [13]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,93 West Main Street,,
2,1003,Walter,White,,298 Drugs Driveway,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,3498 Super Lane,Y,,3498 Super Lane,,
18,1019,Creed,Braton,,,,Y,,,
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

# The call centre staff also requested a list of phone numbers they can call

In [18]:
for x in df.index:
    if df.loc[x, 'Do_Not_Contact'] == 'Y':
        df.drop(x, inplace=True)

In [19]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,93 West Main Street,,
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,,
18,1019,Creed,Braton,,,,Y,,,